services:
  php-fpm:
    build:
      context: .
      dockerfile: build/test/Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: build/dev/Dockerfile-nginx
    ports:
      - 80:80